name: Docker Images One

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Configure Docker to use HTTP for private registry
      run: |
        echo '{"insecure-registries":["192.168.10.101:5000"]}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker

    - name: Pull MySQL image from Docker Hub
      run: docker pull konradkleine/docker-registry-frontend:v2

    - name: Tag MySQL image for private registry
      run: docker tag konradkleine/docker-registry-frontend:v2 192.168.10.101:5000/docker-registry-frontend:v2

    - name: Push MySQL image to private registry
      run: docker push 192.168.10.101:5000/docker-registry-frontend:v2
